{{- if .Values.client.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.client.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.client.name }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      restartPolicy: Never
      containers:
      - name: client
        image: {{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        env:
        - name: SERVER_URL
          value: {{ .Values.client.serverUrl | quote }}
        command: ["/app/client"]
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /spire/agent-socket
          readOnly: true
        - name: config
          mountPath: /app/e5s.yaml
          subPath: e5s.yaml
      volumes:
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
      - name: config
        configMap:
          name: {{ .Values.config.name }}
{{- end }}
