{{- if .Values.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "e5s-demo.fullname" . }}-server-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "e5s-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
data:
  e5s.yaml: |
    {{- toYaml .Values.server.config | nindent 4 }}
{{- end }}
---
{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "e5s-demo.fullname" . }}-client-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "e5s-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
data:
  e5s.yaml: |
    {{- toYaml .Values.client.config | nindent 4 }}
{{- end }}
