{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "e5s-demo.fullname" . }}-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "e5s-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "e5s-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}
